version: '3.8'

services:
  kadastr-api:
    build: .
    container_name: kadastr-api
    restart: always
    hostname: kadastr-api
    networks:
      kadastr-be:
        ipv4_address: 172.30.50.10
    env_file:
      - .env
    depends_on:
      kadastr-pgsql:
         condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

  kadastr-pgsql:
#    image: postgres:18.1
    image: postgis/postgis:18-3.6
    container_name: kadastr-pgsql
    hostname: kadastr-pgsql
    restart: always
    environment:
      TZ: '${APP_TIME_ZONE}'
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      DB_SYNCHRONIZE: '${DB_SYNCHRONIZE}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      kadastr-be:
        ipv4_address: 172.30.50.100
    volumes:
      - 'kadastr-pgsql:/var/lib/postgresql/'
networks:
  kadastr-be:
    ipam:
      config:
        - subnet: 172.30.50.0/24

volumes:
  kadastr-pgsql: